# Generated by Django 5.2 on 2025-04-21 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='trimestre',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='academics.trimestre'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'academic_year', 'grade_level', 'paralelo')},
        ),
        migrations.AlterUniqueTogether(
            name='trimestre',
            unique_together={('academic_year', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('trimestre', 'number')},
        ),
    ]
